import type { IndexDocument, IndexDocumentTreeGroup, IndexDivergenceSummary } from "../types";

import {
  currentEnvelope,
  extractSection,
  finalizeParsed,
  makeParseError,
  parseFailure,
  type ParseResult,
} from "./shared";

function parseDecisionLog(section: string | undefined): string[] {
  if (!section || /_\(No decisions recorded yet\)_/m.test(section)) {
    return [];
  }

  return section
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("- "))
    .map((line) => line.replace(/^-\s+/, ""));
}

function parseDivergenceSummary(section: string): IndexDivergenceSummary {
  const summary: IndexDivergenceSummary = {
    open: 0,
    proposed: 0,
    resolved: 0,
    notes: [],
  };

  for (const rawLine of section.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line.startsWith("- ")) {
      continue;
    }

    const content = line.replace(/^-\s+/, "");
    const countsMatch = content.match(/open:\s*(\d+)\s*\|.*proposed:\s*(\d+)\s*\|.*resolved:\s*(\d+)/i);
    if (countsMatch) {
      summary.open = Number.parseInt(countsMatch[1], 10);
      summary.proposed = Number.parseInt(countsMatch[2], 10);
      summary.resolved = Number.parseInt(countsMatch[3], 10);
      continue;
    }

    const fullyClosedMatch = content.match(/fully-closed:\s*(\d+)/i);
    if (fullyClosedMatch) {
      summary.fullyClosed = Number.parseInt(fullyClosedMatch[1], 10);
      continue;
    }

    summary.notes.push(content);
  }

  if (summary.open === 0 && summary.proposed === 0 && summary.resolved === 0 && summary.notes.length > 0) {
    for (const note of summary.notes) {
      if (/\(open,/i.test(note)) {
        summary.open += 1;
      } else if (/\(proposed,/i.test(note)) {
        summary.proposed += 1;
      } else if (/\(resolved,/i.test(note)) {
        summary.resolved += 1;
      } else if (/\(fully-closed,/i.test(note)) {
        summary.fullyClosed = (summary.fullyClosed || 0) + 1;
      }
    }
  }

  return summary;
}

function parseSignalsSummary(section: string | undefined): string[] {
  if (!section || /_\((No active signals|No signals recorded in this legacy fixture)\)_/m.test(section)) {
    return [];
  }

  return section
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("- "))
    .map((line) => line.replace(/^-\s+/, ""));
}

function parseDocumentTree(section: string): IndexDocumentTreeGroup[] {
  const groups: IndexDocumentTreeGroup[] = [];
  let currentGroup: IndexDocumentTreeGroup | undefined;

  for (const rawLine of section.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) {
      continue;
    }

    const headingMatch = line.match(/^###\s+([a-z0-9-]+)$/);
    if (headingMatch) {
      currentGroup = {
        collaborator: headingMatch[1],
        documents: [],
      };
      groups.push(currentGroup);
      continue;
    }

    const documentMatch = line.match(/^-\s+`([^`]+)`\s+[—-]\s+(.+)$/);
    if (documentMatch && currentGroup) {
      currentGroup.documents.push({
        path: documentMatch[1],
        summary: documentMatch[2],
      });
    }
  }

  return groups;
}

export function parseIndex(text: string): ParseResult<IndexDocument> {
  const generatedMatch = text.match(/^_Generated by ([a-z-]+) @ ([0-9T:-]+Z)_$/m);
  if (!generatedMatch) {
    return parseFailure([
      makeParseError("PX-P001", text, "_Generated by", "Missing generated banner."),
    ]);
  }

  const northStarSection = extractSection(text, "North Star");
  const divergencesSection = extractSection(text, "Divergences");
  const documentTreeSection = extractSection(text, "Document Tree");
  if (!northStarSection || !divergencesSection || !documentTreeSection) {
    return parseFailure([
      makeParseError("PX-P001", text, "## ", "Missing one or more required INDEX sections."),
    ]);
  }

  const northStarLines = northStarSection
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
  const northStar = northStarLines
    .filter((line) => line.startsWith(">") && !line.includes("_Source:"))
    .map((line) => line.replace(/^>\s*/, "").trim())
    .join(" ");
  const northStarSource = northStarLines
    .find((line) => /_Source:/i.test(line))
    ?.replace(/^>\s*/, "")
    .replace(/^_Source:\s*/i, "")
    .replace(/_$/g, "")
    .trim();

  return finalizeParsed("index-doc", text, {
    envelope: currentEnvelope({
      generator: generatedMatch[1],
      generatedAt: generatedMatch[2],
    }),
    northStar,
    northStarSource,
    decisionLog: parseDecisionLog(extractSection(text, "Decision Log (last 3)")),
    divergences: parseDivergenceSummary(divergencesSection),
    signals: parseSignalsSummary(extractSection(text, "Signals")),
    documentTree: parseDocumentTree(documentTreeSection),
  });
}